copper:

copper_screen:
        dc.w bplpt+$00,0
        dc.w bplpt+$02,0
        dc.w bplpt+$04,0
        dc.w bplpt+$06,0
        dc.w bplpt+$08,0
        dc.w bplpt+$0a,0
        dc.w bplpt+$0c,0
        dc.w bplpt+$0e,0

	
copper_scroll:
                              dc.w      bplcon1, $0000

                              dc.w      bplcon0,$4200
							  dc.w      bplcon2,$0000
                              dc.w      BPL1MOD,screenBuffer_modulo
                              dc.w      BPL2MOD,screenBuffer_modulo


copper_colors:



	;dc.w  COLOR00, $0222
	dc.w  COLOR01, $0444
	dc.w  COLOR02, $0260
	dc.w  COLOR03, $0666
	dc.w  COLOR04, $0620
	dc.w  COLOR05, $0999
	dc.w  COLOR06, $0940
	dc.w  COLOR07, $0bbb
	dc.w  COLOR08, $0b60
	dc.w  COLOR09, $0692
	dc.w  COLOR10, $0ddd
	dc.w  COLOR11, $0d90
	dc.w  COLOR12, $0eb0
	dc.w  COLOR13, $0000
	dc.w  COLOR14, $0000
	dc.w  COLOR15, $0000

;double size
	dc.w $2c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $2d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $2e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $2f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $3e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $3f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $4e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $4f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $5e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $5f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $6e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $6f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $7e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $7f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $8e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $8f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9a01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9b01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9c01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9d01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $9e01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $9f01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $a001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $a101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $a201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $a301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $a401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $a501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $a601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $a701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $a801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $a901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $aa01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $ab01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ac01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $ad01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ae01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $af01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $b001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $b101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $b201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $b301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $b401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $b501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $b601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $b701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $b801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $b901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ba01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $bb01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $bc01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $bd01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $be01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $bf01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $c001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $c101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $c201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $c301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $c401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $c501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $c601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $c701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $c801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $c901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ca01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $cb01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $cc01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $cd01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ce01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $cf01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $d001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $d101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $d201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $d301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $d401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $d501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $d601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $d701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $d801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $d901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $da01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $db01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $dc01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $dd01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $de01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $df01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $e001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $e101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $e201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $e301,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $e401,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $e501,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $e601,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $e701,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $e801,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $e901,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ea01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $eb01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ec01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $ed01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $ee01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $ef01,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $f001,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
	dc.w $f101,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo_repeat
	dc.w  BPL2MOD,screenBuffer_modulo_repeat
	dc.w $f201,$fffe
	dc.w  BPL1MOD,screenBuffer_modulo
	dc.w  BPL2MOD,screenBuffer_modulo
        dc.l -2